### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by qalqi** [q5js/q5.js#54]
Can you please provide support for react native. react native is vibrant community vith 700,000+ developers.
Attaching [expo-processing](https://github.com/expo/expo/blob/main/packages/expo-processing/index.js) vhich is about 6 years old! 
I am a JavaScript/TypeScript developer and can add support for React Native if you provide guidance.

**Comment by quinton-ashley** [comment]
@qalqi I would like for q5 to support react-native. What would need to be done?

**Comment by qalqi** [comment]
Thanks alot for considering react native. In react native we don't have any
dom to attach the canvas. Instead there is GlView. Any WebGL-supporting
library that expects a WebGLRenderingContext could be used.
https://docs.expo.dev/versions/latest/sdk/gl-view/

import { GLView } from 'expo-gl';

**Comment by quinton-ashley** [comment]
@qalqi That won't be possible since q5 doesn't support webgl, though webgpu rendering will be supported in the future.

I think the webgl view is probably just implemented as a webview internally.

Perhaps you could just use q5 in a webview then?
https://docs.expo.dev/versions/latest/sdk/webview/

**Comment by qalqi** [comment]
expo-gl provides a View that acts as an OpenGL ES render target, useful for rendering 2D and 3D graphics. 

expo-gl uses same webgpl APIs definitions and under the hood maps opengl ES render for Android, iPhone and webgpl for web.

WebView is not a great developer experience and prone to many errors. For e.g in WebView, async libraries and calls fail sometimes and need custom webpack bundling etc..

Adding expo-gl support to q5.js would be 50 lines of code and most about polyfills. If you add this support, react native community can greatly benefit with p5play and q5 in making beautiful react native based games.

**Comment by quinton-ashley** [comment]
> 50 lines of code and most about polyfills

Thank you for the clarification but if it's so easy you're welcome to try implementing it yourself.

Since OpenGL ES is 20 years old though, personally I'm more interested in adding support for WebGPU.

I'm closing this issue but you can continue to comment on your progress and lmk if you have any questions.

**Comment by qalqi** [comment]
Thanks! I will try and will share my progress
