### ISSUE TITLE
Failure function callback not called when loadImage fails to load image

### ISSUE THREAD

**Issue by pvzzombs** [q5js/q5.js#55]
**Replication link**:  [jsfiddle](https://jsfiddle.net/mozL92s7/2/)

**Javascript code:**
```js
function success() {
  alert("Success");
}

function fail() {
  alert("Fail");
}

function preload() {
  loadImage("doesnotexist.png", success, fail);
}

function setup() {
  createCanvas(200, 200);
}

function draw() {
  background(128);
}
```

### Actual behavior: 
- failure function callback _not called_
### Expected behavior: 
- failure function callback _must be called_

**Comment by pvzzombs** [comment]
Here is the reference: [https://p5js.org/reference/p5/loadImage/](https://p5js.org/reference/p5/loadImage/)

**Comment by quinton-ashley** [comment]
q5's `loadImage` doesn't accept a failure callback, it will simply throw an error to the js console. In q5 the third param to `loadImage` is a canvas options object.

I will note this as a difference from p5's api in the readme.md.
