### ISSUE TITLE
`p5.Vector` `setHeading()` function missing

### ISSUE THREAD

**Issue by Dukemz** [q5js/q5.js#60]
The setHeading() method on vectors hasn't been implemented yet. The slerp() method appears to be missing too.

There might be some other properties that also don't exist yet but I'm not sure which ones.

**Comment by quinton-ashley** [comment]
https://p5js.org/reference/p5.Vector/setHeading/

**Comment by quinton-ashley** [comment]
I'm working on implementing these now

**Comment by quinton-ashley** [comment]
implemented in v2.2.4
