### ISSUE TITLE
createCanvas variable/element, show createGraphics

### ISSUE THREAD

**Issue by neue** [q5js/q5.js#96]
Trying to do things like the following with Q5, think there is value in being able to address the canvas element created by createCanvas like this, also think being able to graduate graphics to an a visible canvas is essential once you're trying to debug a chain of graphics canvases or build creative tooling where one interactable canvas influences another.

```
let mycanvas, mygraphics;
function setup() {
  mycanvas = createCanvas(400, 400);
  mycanvas.background(255, 227, 7);
  mycanvas.elt.oncontextmenu = () => false;

  mygraphics = createGraphics(200, 200);
  mygraphics.show();
  mygraphics.background(255, 7, 7);
}

function draw(){
    image(mygraphics,100,0);
}
```

**Comment by quinton-ashley** [comment]
No, `createCanvas` returns the canvas element directly in q5.

If you want the Q5 instance do this:


```js
let q = new Q5();

q.createCanvas();
q.background("green");
```
